src_data: /Vol1/dbstore/datasets/multimodal/youtube/numpy/video_level_folds
model: youtube8m.video_level_nn_models.models.ResNetLike
model_kwargs: {}
dataset_reader: youtube8m.video_level_nn_models.chunked_dataset.make_video_audio_labels_dataset
batch_size: 1024 
mixup_class: youtube8m.video_level_nn_models.mixup_dataloader.DataLoaderWithMixUp
mixup_args:
  alpha: 0.4
train_kwargs:
  # max_batches_per_epoch: 1000
  epochs: 100
  lr_scheduler_ctor: torch.optim.lr_scheduler.ReduceLROnPlateau
  lr_scheduler_kwargs:
    factor: 0.5
    patience: 3
    verbose: true
  optimizer_ctor: torch.optim.Adam
  optimizer_kwargs:
    lr: 0.005
  train_metrics_def: youtube8m.utils.training.FAST_METRICS
  val_metrics_def: youtube8m.utils.training.FULL_METRICS
  #criterion: torch.nn.functional.binary_cross_entropy
  criterion: youtube8m.utils.losses.binary_cross_entropy_weighted
  #criterion: torch.nn.SmoothL1Loss
