src_data: /Vol1/dbstore/datasets/multimodal/youtube/numpy/video_level_folds
model: youtube8m.video_level_nn_models.models.ResNetLike
model_kwargs: {av_id_block_num: 3, concat_id_block_num: 3, dropout: 0., inner_size: 400}
dataset_reader: youtube8m.video_level_nn_models.chunked_dataset.make_video_audio_labels_dataset
batch_size: 64000
train_kwargs:
  epochs: 500
  lr_scheduler_ctor: torch.optim.lr_scheduler.ReduceLROnPlateau
  lr_scheduler_kwargs:
    factor: 0.5
    patience: 0
    verbose: True
  optimizer_ctor: torch.optim.Adam
  optimizer_kwargs:
      lr: 0.001
  train_metrics_def: youtube8m.utils.training.FAST_METRICS
  val_metrics_def: youtube8m.utils.training.FULL_METRICS
  max_batches_per_epoch: 20
  max_batches_per_val: 2
  print_metrics_frequency: 2
use_parallel_dataloader: True
parallel_dataloader_train_kwargs: {process_count: 1, max_queue_size: 10, epoch_size: 100000000000000000}
