src_data: /Vol1/dbstore/datasets/multimodal/youtube/numpy/frame_level_folds/
model: youtube8m.sequence_models.models.EarlyConcatTransformerClassifier
model_kwargs:
  inner_size: 500
  dropout: 0.0
  layers_n: 1
  heads_n: 1
  max_length: 303
dataset_reader: youtube8m.sequence_models.dataset.make_frame_level_video_audio_labels_dataset
batch_size: 512
use_parallel_dataloader: true
parallel_dataloader_train_kwargs:
  epoch_size: 500000000
  process_count: 2
  max_queue_size: 2
train_kwargs:
  max_batches_per_epoch: 500
  max_batches_per_val: 100
  print_metrics_frequency: 100
  epochs: 100
  early_stopping_patience: 15
  lr_scheduler_ctor: torch.optim.lr_scheduler.ReduceLROnPlateau
  lr_scheduler_kwargs:
    factor: 0.5
    patience: 1
    verbose: true
  optimizer_ctor: torch.optim.Adam
  optimizer_kwargs:
    lr: 0.001
    #weight_decay: 0.000001
  train_metrics_def: youtube8m.utils.training.FAST_METRICS
  val_metrics_def: youtube8m.utils.training.FULL_METRICS
  criterion: torch.nn.functional.binary_cross_entropy_with_logits
