src_data: /Vol1/dbstore/datasets/multimodal/youtube/numpy/video_level_folds
model: youtube8m.video_level_nn_models.models.ResNetLike
model_kwargs:
  dropout: 0.3
  av_id_block_num: 2
  concat_id_block_num: 2
  inner_size: 2048
  context_gating: True
dataset_reader: youtube8m.video_level_nn_models.chunked_dataset.make_video_audio_labels_dataset
mixup_class: youtube8m.video_level_nn_models.mixup_dataloader.DataLoaderWithMixUp
mixup_args:
    alpha: 0.3
batch_size: 4096 
train_kwargs:
  early_stopping_patience: 100
  max_batches_per_epoch: 2000
  max_batches_per_val: 300
  epochs: 30
  lr_scheduler_ctor: torch.optim.lr_scheduler.ReduceLROnPlateau
  lr_scheduler_kwargs:
    factor: 0.5
    patience: 1
    verbose: true
  optimizer_ctor: torch.optim.Adam
  optimizer_kwargs:
    lr: 0.02
  train_metrics_def: youtube8m.utils.training.FAST_METRICS
  val_metrics_def: youtube8m.utils.training.FULL_METRICS
  criterion: torch.nn.functional.binary_cross_entropy_with_logits
