src_data: /Vol1/dbstore/datasets/multimodal/youtube/numpy/frame_level_folds
val_data: /Vol1/dbstore/datasets/multimodal/youtube/numpy/frame_level_folds
model: youtube8m.sequence_models.models.AttentionModel4
model_kwargs: {}
dataset_reader: youtube8m.sequence_models.dataset.make_frame_level_video_audio_labels_dataset #youtube8m.video_level_nn_models.chunked_dataset.make_video_audio_labels_dataset
batch_size: 400
use_parallel_dataloader: true
parallel_dataloader_train_kwargs:
  epoch_size: 500000000
  process_count: 3
  max_queue_size: 3
train_kwargs:
  print_metrics_frequency: 100
  early_stopping_patience: 100
  max_batches_per_epoch: 1000
  max_batches_per_val: 200
  epochs: 50
  lr_scheduler_ctor: torch.optim.lr_scheduler.ReduceLROnPlateau
  lr_scheduler_kwargs:
    factor: 0.5
    patience: 0
    verbose: true
  optimizer_ctor: torch.optim.Adam
  optimizer_kwargs:
    lr: 0.001
  train_metrics_def: youtube8m.utils.training.FAST_METRICS
  val_metrics_def: youtube8m.utils.training.FULL_METRICS
  criterion: torch.nn.functional.binary_cross_entropy_with_logits
